# Generated by Django 4.1 on 2024-07-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0003_dish_image_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="cook",
            name="image_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
