# Generated by Django 4.2.14 on 2024-07-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0004_cook_image_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="image_name",
            field=models.ImageField(default="default_cook", upload_to=""),
        ),
    ]
