# Generated by Django 4.2.14 on 2024-07-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0005_alter_cook_image_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="cook",
            name="image",
            field=models.ImageField(default="default_cook", upload_to=""),
        ),
    ]
