# Generated by Django 4.2.14 on 2024-07-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0006_cook_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="image",
            field=models.ImageField(default="default_cook.jpg", upload_to=""),
        ),
        migrations.AlterField(
            model_name="cook",
            name="image_name",
            field=models.ImageField(default="default_cook.jpg", upload_to=""),
        ),
    ]
