# Generated by Django 4.2.14 on 2024-07-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0008_remove_cook_image_alter_cook_image_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="image_name",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="dish",
            name="image_name",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
