"""
Django settings for restaurant_kitchen_service project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "'django-insecure-xmlp@%r&$%%!$c#4s+mdy4uk=e!5jtc$squ+6l$kxc_s0*ol8i'")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "") != "False"

ALLOWED_HOSTS = ["127.0.0.1", "localhost", "restaurant-kitchen-service-t6uy.onrender.com"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "debug_toolbar",
    "kitchen",
    "crispy_forms",
    "crispy_bootstrap4",
    "theme_material_kit",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "restaurant_kitchen_service.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "restaurant_kitchen_service.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}
#dropbox
# DEFAULT_FILE_STORAGE = "storages.backends.dropbox.DropboxStorage"
# DROPBOX_OAUTH2_TOKEN = "sl.B5shU1TWZowoaOh68fE-226pM4bLlSv_BrqOr-aUAQrPj42EzklXKLM9qgyRU9uanub3UCq2Cxk5WqqIfJ2Zae9DZsSJ0fd4KNlj8WuX0pORwxaNC2yWW7sqGbOqUYAbw-o4yFd9eRmZDRZaPIs0ST4"
# DROPBOX_ROOT_PATH = "/media_project"

db_from_env = dj_database_url.config(conn_max_age=500)
DATABASES["default"].update(db_from_env)

DATABASE_URL = "postgresql://filling_owner:MOYk0piqUg4z@ep-solitary-unit-a2qnjoed.eu-central-1.aws.neon.tech/filling?sslmode=require"

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]
# MEDIA_URL = "/media/"
# MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "kitchen.Cook"

LOGIN_REDIRECT_URL = "/"

INTERNAL_IPS = [
    "127.0.0.1",
]

CRISPY_TEMPLATE_PACK = "bootstrap4"

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# DEFAULT_FILE_STORAGE = "storages.backends.dropbox.DropboxStorage"
# STATICFILES_STORAGE = "storages.backends.dropbox.DropboxStorage"
# DROPBOX_OAUTH2_TOKEN = "sl.B5lGiG-4HDeP845F2xfjJSVc1qvah_mZXJkQBjAV0Uii6_TJ94pydItcrCy6OLx1-W8OpnjYnsjNvpyuQFqmaUPq51-9ejzielojOTYuYTGycoXlK6OfIr-QGBJcEodaWbMDm66XAbpY"
# DROPBOX_OAUTH2_REFRESH_TOKEN = "-iQS3myJ-KUAAAAAAAAAAWz5rRJmjtCeDmNaNpW2Z67Xu3POpTGkccyKMENLDfGj"
# DROPBOX_ACCESS_TOKEN = "sl.B5lowacyoviEzEW7jf4GpMxSSI_rvG_zVVf4NH92YMX2VR8biwyygpXi86pdin2hyhbbwFfSqhLVOvFXFQyjZ6OPqw9UbOIfh6Jy-3j0kWOIJqnfGwtvofwfFlUMsrFT8XYeS58N3UG0"
# DROPBOX_APP_SECRET = "7dzbfwaxfh7064b"
# DROPBOX_APP_KEY = "p0a3p8kfi1twyfu"

# STORAGES = {
#     "default": {
#         "BACKEND": "storages.backends.dropbox.DropboxStorage",
#         "OPTIONS": {
#             "oauth2_access_token": "sl.B5pbR69GsiV54rhZDd08GW0BuxGTzvtupwGQ7lLK-X2t4FAR_L6M3vRLRa9P3ys9VUAgErgkQ_8LbG68Iso6kxS557SLsUTlxHO6HisTR5C0WpLrl6_oOlA_JVRGzOggrsGvf9v3NqQgs9srrCpOnC8",
#             "oauth2_refresh_token": "-iQS3myJ-KUAAAAAAAAAAWz5rRJmjtCeDmNaNpW2Z67Xu3POpTGkccyKMENLDfGj",
#             "app_secret": "7dzbfwaxfh7064b",
#             "app_key": "p0a3p8kfi1twyfu",
#             "root_path": "/media/"
#         },
#     },
#     "staticfiles": {
#         "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
#     },
# }
